name: Hello world using java script action

on: [push]

jobs:
  hello_world_action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
            who-to-greet: Raghav
      - name: The time we greeted you
        run: echo "The time was ${{ steps.hello.outputs.time }}" 



